Implement applyMiddlewares
glung/redux-java pull request #19
Opened 2017-02-24 16:38 UTC by mkaulig

Implement a method applyMiddlewares inspired by the redux function with
the same name. This method returns an enhancer, which can enhance store
creators to execute the applied middlewares before normal dispatch
calls.

2017-03-26 16:16 UTC, glung requested changes
Sorry totally missed your PR ! Thx for contributing 

Could you add tests ?

2017-03-26 16:16 UTC, glung commented on lib/src/main/java/com/glung/redux/Middlewares.java
> +            return createMiddlewareDispatcher(middlewares).dispatch(action);
Do you think we could create the Dispatcher it only once by calling `createMiddlewareDispatcher` in `applyMiddlewares` ?

2017-03-27 03:06 UTC, AngusMorton commented on lib/src/main/java/com/glung/redux/Middlewares.java
> +        private Dispatcher createMiddlewareDispatcher(final List<redux.api.enhancer.Middleware<S>> middlewares) {
This method should be static

2017-04-03 17:15 UTC, mkaulig commented
Thanks for the feedback! I added some Tests and changed the implementation to create the ```Dispatcher``` only once in ```applyMiddlewares```

2017-04-05 22:05 UTC, glung commented
Hey @mkaulig just a message to say I am not ignoring this PR, it will look into it asap

2017-04-11 15:55 UTC, glung approved these changes
Thx! I am just going to apply some minor style related changes on master after landing it

2017-04-11 15:55 UTC, merged